### ISSUE TITLE
VIVO-1032: Enable property template model to return whether or not the property is a faux property

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2716]
[Huda Khan](https://github.com/hudajkhan) (Migrated from [VIVO-1032](https://vivo-project.atlassian.net/browse/VIVO-1032)) said:

The property template model JAVA object does not currently have a method which would allow Freemarker to retrieve information about whether or not the item is a faux property.  I am adding a method to enable retrieval of a boolean flag indicating whether or not the property represented by the template model object is a faux property.

This information will also be made available in a JSON view of the information sent to the Freemarker template (in a linked issue).

**Comment by chenejac** [comment]
This issue is related to #2717

**Comment by hudajkhan** [comment]
This issue was created to be able to retrieve information on whether or not a particular property was a Faux property by directly querying the Property Template Model object.  Unless other use cases (beyond the original) exist for this issue, it is ok to close it.
