### ISSUE TITLE
VIVO-1101: Create optional modules for Datastar research data and metadata representation

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2785]
[Jon Corson-Rikert](https://github.com/jcorson55) (Migrated from [VIVO-1101](https://vivo-project.atlassian.net/browse/VIVO-1101)) said:

Moved over to this Jira from https://issues.library.cornell.edu/browse/VIVOONT-404

Not open in Github at this time.

**Comment by hudajkhan** [comment]
This issue is related to the Datastart project from several years ago which is no longer active and can be closed.
