### ISSUE TITLE
VIVO-1116: Search fails with Certain Unicode

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2800]
[Nate Prewitt](https://github.com/nateprewitt) (Migrated from [VIVO-1116](https://vivo-project.atlassian.net/browse/VIVO-1116)) said:

If you try to search with special characters (I tried á and 🍌) VIVO returns a different unicode string and several, seemingly unrelated, search results. If you try to navigate through these results the string concatenates itself for the next page which quickly results in a "Request Entity Too Large" error in the search module. This is obviously a pretty rare edge case, but I just wanted to make note of it for a possible future fix.

**Comment by hauschke** [comment]
I cannot replicate that with VIVO 1.14. If it cannot be replicated by others with a vanilla VIVO, we might close this issue.

**Comment by chenejac** [comment]
I think search form worked with a HTTP Get request in the past, and there might be some issue with unicode. However, I am quite sure we don't have any issue with Unicode in the search in VIVO, therefore I will close this issue.
