### ISSUE TITLE
VIVO-1219: Move OWL/RDF files to a dedicated GitHub repository

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2810]
[Shahim Essaid](https://vivo-project.atlassian.net/jira/people/5c7706a2ec061e1e4322eb2b) (Migrated from [VIVO-1219](https://vivo-project.atlassian.net/browse/VIVO-1219)) said:

A placeholder issue to discuss and plan for moving the VIVO ontology files to a dedicated GitHub repository. This will be discussed during an upcoming OpenRIF meetings.

**Comment by hauschke** [comment]
https://github.com/vivo-ontologies/vivo-ontology exists, maybe this can be closed.

**Comment by chenejac** [comment]
agree
