### ISSUE TITLE
VIVO-1345: Add confirmedOrcidId

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2936]
[Mike Conlon](https://github.com/mconlon17) (Migrated from [VIVO-1345](https://vivo-project.atlassian.net/browse/VIVO-1345)) said:

confirmedOrcidId is a property in running VIVO systems, but is not found in the VIVO-ISF.  Needs to be added.

https://github.com/openrif/vivo-isf-ontology/issues/719

**Comment by hauschke** [comment]
The requested property is part of the VIVO ontology: https://github.com/vivo-ontologies/vivo-ontology/blob/241c9cac3185ddf94c3b1f39eb74977deac73e5d/vivo.owl#L1681

This issue can be closed.
