### ISSUE TITLE
VIVO-1409: Support serialization options in Jena2tools and jena3tools 

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3000]
[Mike Conlon](https://github.com/mconlon17) (Migrated from [VIVO-1409](https://vivo-project.atlassian.net/browse/VIVO-1409)) said:

Jena2tools and jena3tools support only only output serialization (TriG).  Adding a command line parameter to allow selection of serialization (ttl, rdf/xml, n3, nt) would great improve the use of these utilities, simplifying data sharing, full export for data analysis, and publishing of data to the linked open data cloud, CTSAsearch and other venues.

TriG would remain the default and would be used for input/output processes such as upgrades.

Other formats are preferred for use cases.

**Comment by hauschke** [comment]
If this is really resolved, this issue can be closed. @chenejac
