### ISSUE TITLE
VIVO-1532: Document the triple store upgrade process

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3122]
[Mike Conlon](https://github.com/mconlon17) (Migrated from [VIVO-1532](https://vivo-project.atlassian.net/browse/VIVO-1532)) said:

VIVO has an existing set of scripts that can be configured to upgrade the triple triple store as needed to match ontological changes.

The scripts can be found in VIVO/webapp/src/main/webapp/WEB-INF/ontologies

VIVO looks in this folder each time it starts to determine if an upgrade is necessary and executes the scripts if it determines and upgrade is needed.

**Comment by chenejac** [comment]
Scripts are available only for older releases of VIVO - https://github.com/vivo-project/VIVO/tree/main/webapp/src/main/webapp/WEB-INF/ontologies

**Comment by gneissone** [comment]
@chenejac 
I'm not really sure why it was necessary for the ontology upgrade scripts to run between 1.6, 1.7, and 1.8 when the ontology didn't change. 

We would likely want to provide this functionality if the ontology were the be updated in the future and it would be nice to have it documented in some capacity, but if nobody is interested in or qualified to take that on at this point, we might as well close the issue.

**Comment by brianjlowe** [comment]
I'll take this one.  I won't be able to get to it right away, but I'll be happy to document how the existing system works.  There's a bunch of useful stuff there that we probably don't want to have to reinvent in the future.

**Comment by chenejac** [comment]
It should be probably under this wiki page - https://wiki.lyrasis.org/display/VIVODOC112x/Upgrading+VIVO
