### ISSUE TITLE
VIVO-1594: Document the artifacts needed to add a new supported language to VIVO

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3184]
[Kitio Fofack](https://github.com/KitioFofack) (Migrated from [VIVO-1594](https://vivo-project.atlassian.net/browse/VIVO-1594)) said:

Here we want to give all instructions to a new VIVO user about what (s)he need to create and where to put them in order to have a new language supported by VIVO.

**Comment by chenejac** [comment]
This issue is related to #3189

**Comment by chenejac** [comment]
@VeljkoMaksimovic: you have recently localized VIVO for Serbian language. Do you think documentation at https://wiki.lyrasis.org/display/VIVODOC112x/Developing+a+New+Interface+Language+for+VIVO is well written and there is a list of artifacts needed to add a new supported language to VIVO? If yes, this issue should be closed, otherwise we should update wiki documentation at https://wiki.lyrasis.org/display/VIVODOC112x/Developing+a+New+Interface+Language+for+VIVO

**Comment by VeljkoMaksimovic** [comment]
The instructions for developers were quite good. If I'm not mistaken, the only thing that was missing was a .n3 file with all of the vivo specific classes (locations, people, events etc.). Will check and correct it if needed.
