### ISSUE TITLE
VIVO-1688: Separate VIVO ontology into own repository

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3278]
[Andrew Woods](https://github.com/awoods) (Migrated from [VIVO-1688](https://vivo-project.atlassian.net/browse/VIVO-1688)) said:

This task is to extract the vivo ontology from the core codebase, moving it into its own Git repository. The ontology project should produce a Maven artifact that the core codebase then depends on.

**Comment by hauschke** [comment]
This issue seems to be solved by the creation of https://github.com/vivo-ontologies/vivo-ontology. We will discuss this in the next ontology call. 

The discussion about vitroAnnotations.n3 should be led separately. 

CC @brianjlowe @litvinovg @tawahle @chenejac
