### ISSUE TITLE
VIVO-1841: SPARQL Update API doesn't support sending update string as non-form-encoded POST body

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3429]
[Brian Lowe](https://github.com/brianjlowe) (Migrated from [VIVO-1841](https://vivo-project.atlassian.net/browse/VIVO-1841)) said:

In the context of the following email discussion

https://groups.google.com/forum/#!topic/vivo-tech/RlPFVvoOenQ

the issue surfaced that SPARQL UPDATE clients that send the update string as the pure post body are not supported by VIVO's update API.  VIVO only supports posting the update string as the www-form-encoded value of the "update" parameter.

Although VIVO's update API does not necessarily bill itself as a genuine SPARQL UPDATE endpoint, it would be good to support both approaches – and, generally, to adhere as closely as possible to the SPARQL UPDATE spec.

**Comment by gneissone** [comment]
See https://github.com/vivo-project/Vitro/pull/252 for pull request that addresses issue.

**Comment by chenejac** [comment]
@gneissone can you please update the [SPARQL update wiki page](https://wiki.lyrasis.org/display/VIVODOC112x/SPARQL+Update+API) in accordance with your contribution.
