### ISSUE TITLE
1.12.1 not building 

### ISSUE THREAD

**Issue by gneissone** [vivo-project/VIVO#3610]
Installing 1.12.1 does not seem to work correctly. Languages don't seem to be included, so if you manage to build the application, VIVO complains about not finding the i18n directory upon startup. 

**Additional context**
Behavior was replicated by @chenejac and @brianjlowe

**Comment by fmdelvalle** [comment]
I could work around this issue by:
1) copying the VIVO/installer directory outside
2) Copying the language files to the installer (these are for Spanish, and assumes the installer is in 'installer' folder, replace as you need):
cp -rf VIVO-languages/es/home/src/main/resources/rdf/i18n/es/* installer/home/src/main/resources/rdf/ &&
cp -rf Vitro-languages/es/webapp/src/main/webapp/* installer/webapp/src/main/webapp/ &&
cp -rf VIVO-languages/es/webapp/src/main/webapp/* installer/webapp/src/main/webapp/ &&
3) building with a custom installer: mvn install -s settings.xml -Dvivo-installer-dir=<path to copied installer folder>

With these I'm able to start the app.
