### ISSUE TITLE
Validation of data provided for execution of an action

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3623]
**Describe the solution you'd like**
Data provided by users for [execution of an action](https://github.com/vivo-project/VIVO/issues/3622) should be encapsulated into [OperationData](https://github.com/litvinovg/Vitro/blob/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/OperationData.java). It should be provided for the certain steps in the custom action, and before it is executed, a validation should be performed. Validators for Parameters are defined in the RDF representation of an action.  

**Describe alternatives you've considered**
A part of validation might be moved in the later phase on client side and performed within JavaScript code (e.g. isNotNull)

**Additional context**
https://github.com/litvinovg/Vitro/tree/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/validators

**Comment by chenejac** [comment]
Probably an interface might be defined for elements which should be validated (similarly as Removable and derrefence, or RunnableComponent and run). The other option might be to extend RunnableComponent with validate method, which basically will pass through associated validators and invoke [isValid method](https://github.com/litvinovg/Vitro/blob/dynapi/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/validators/Validator.java#L7).

Can we introduce notation for definition validation rules or use some existing notation to make list of validators easy for customization by non-Java developers?

**Comment by litvinovg** [comment]
There are data types and data formats in OpenAPI Specification. I think we should use formats to specify RDF data types and other restrictions.
