### ISSUE TITLE
Dockerfile fails to copy vivo home

### ISSUE THREAD

**Issue by wwelling** [vivo-project/VIVO#3643]
**Describe the bug**

```
=> ERROR [4/6] COPY ./installer/home/target/vivo /vivo-home                                                                    0.0s
```

**To Reproduce**

Follow https://github.com/vivo-project/VIVO#docker-compose

**Expected behavior**

Should build images and run VIVO.

**Screenshots**

![image](https://user-images.githubusercontent.com/8352733/153906765-66ce12e8-e70b-4979-9618-5f669426d49b.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Tomcat version: N/A
 - VIVO version: master
 - Apache Solr or ElasticSearch version: N/A

**Additional context**

**Comment by wwelling** [comment]
It does but will break on next version change.

**Comment by wwelling** [comment]
Also, I checked 1.12.1-maint Dockerfile and it does not have that change but the pom does have that change.

**Comment by wwelling** [comment]
https://github.com/vivo-project/VIVO/pull/3644

**Comment by gneissone** [comment]
The commit history on that PR is confusing. The relevant change is re-adding `<finalName>${app-name}</finalName>` to installer/home/pom.xml, the change to the Dockerfile was added then removed. That pom tag results in the target home directory being named `vivo` instead of `vivo-installer-home-x.x.x`

**Comment by wwelling** [comment]
This works from `rel-1.12.1-maint` branch. Closing. Shouldn't the default branch in GitHub being the development branch? I sense some disarray still.
