### ISSUE TITLE
ChangeListeners get the same model change

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3647]
**Describe the bug**
[ChangeListener](https://github.com/vivo-project/Vitro/blob/39e1eed20df592e8c0b62834d34042bc4d370ae3/api/src/main/java/edu/cornell/mannlib/vitro/webapp/rdfservice/ChangeListener.java#L16)'s  [receive](https://github.com/vivo-project/Vitro/blob/39e1eed20df592e8c0b62834d34042bc4d370ae3/api/src/main/java/edu/cornell/mannlib/vitro/webapp/rdfservice/impl/RDFServiceImpl.java#L147) the same modelChanges, which is not thread-safe and causes difficulties while working with [serialized model](https://github.com/vivo-project/Vitro/blob/39e1eed20df592e8c0b62834d34042bc4d370ae3/api/src/main/java/edu/cornell/mannlib/vitro/webapp/rdfservice/impl/ModelChangeImpl.java#L36). 

**To Reproduce**
1. Create two ChangeListeners
2. Use getSerializedModel in both listeners to get serialized model changes 
4. See that only the first one recieves model changes as the InputStream is read by first one.

**Expected behavior**
The ChangeListener should receive model changes that are not affected by other ModelChangeListener actions.
Both ChangeListeners should receive serialized model changes.

**Comment by brianjlowe** [comment]
We should see how this relates to https://github.com/vivo-project/VIVO/issues/3129 and what might have changed in the meantime.
