### ISSUE TITLE
Link Ontology classes with implementations

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3659]
The Ontology class should be mapped to a Java class by using this [n3 file](https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb/home/src/main/resources/rdf/tbox/filegraph/dynamic-api-implementation.n3)

**Task**
- [x] Add SolrQuery

**Comment by VeljkoMaksimovic** [comment]
I think this is done with this [PR](https://github.com/vivo-project/Vitro/pull/267)
