### ISSUE TITLE
Duplicated faux properties every time

### ISSUE THREAD

**Issue by fmdelvalle** [vivo-project/VIVO#3680]
**Describe the bug**
Creating faux properties, either from VIVO web or by introducing .n3, makes these properties show twice. They can show in the same properties tab or on different ones, depending on configuration.

I am defining an ObjectProperty in a tbox/filegraph .n3 file, and a ConfigContext and an ObjectPropertyDisplayConfig in a display/everytime .n3 file (see below). They load properly and they are similar to the ones produced by VIVO web. 

Vitro GroupedPropertyList.java builds an initial list of ObjectProperties based on whether there is some object for the property. As the property does have assigned values, it is added here for the first time. Then, this class calls getAdditionalFauxPropertiesForList(), that finds the context and the configuration and adds the property for the second time. So, the same property is added twice to propertyList. This seems like a bug to me: if there is a faux property, the initial ObjectProperty should be removed. 
I can't find any combination that makes the initial match be skipped and the second match to succeed, nor there is any code that removes these duplicates.

**To Reproduce**
Example tbox/filegraph entry:

`myns:hasAwardedDegree a owl:ObjectProperty .`

(adding rdfs:domain and rdfs:range does not change anything. Defining vitro:inPropertyGroupAnnot sets where the first match goes, but does not affect the second, and they're not joined anywhere)

Example display/everytime entry:

```
local:hasAwardedDegreeContext a config:ConfigContext ;
    config:hasConfiguration local:hasAwardedDegreeConfig ;
    config:configContextFor myns:hasAwardedDegree ;
    config:qualifiedByDomain foaf:Person ;
    config:qualifiedBy vivo:AwardedDegree .

local:hasAwardedDegreeConfig a config:ObjectPropertyDisplayConfig ;
    config:listViewConfigFile "listViewConfig-hasAwardedDegree.xml"^^xsd:string ;
    config:displayName "Awarded degrees" ;
    rdfs:label "hasAwardedDegree" ;
    vitro:displayRankAnnot 10;
    vitro:hiddenFromDisplayBelowRoleLevelAnnot role:public ;
    vitro:prohibitedFromUpdateBelowRoleLevelAnnot role:public ;
    vitro:stubObjectPropertyAnnot "true"^^xsd:boolean ;
    config:propertyGroup vitrogroup:vitroPropertyGroupoverview .
```

Any triple like:
`<subject> ns:hasAwardedDegree <object>`

will trigger this effect.

**Expected behavior**
Faux properties should appear only once. They are showing in the defined tab, and in the Others default tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/3813576/156434522-0505a154-272d-4b3e-adf5-b43688c58145.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Tomcat version 9
 - VIVO version 1.12 snapshot
 - Apache Solr 8.11

**Additional context**
There should be a clear example in the documentation about the required triples for a faux property. They cannot be redefined on every installation, and there are several namespaces involved, several conflicting attributes (vitro:inPropertyGroupAnnot, vitro:inClassGroup,config:propertyGroup), and strange behaviors when something is not perfectly set.

**Comment by chenejac** [comment]
This should be fixed in VIVO  1.14.0
