### ISSUE TITLE
Using the database with the VIVO container

### ISSUE THREAD

**Issue by max1c** [vivo-project/VIVO#3682]
This is not really a bug report but more of a question. Can someone point me to documentation on how to use the database with the container? I have created a new miradb database with docker-compose and imported the backup. But how do I plug this database into the VIVO container?

**Comment by chenejac** [comment]
Apologies for missing this issue/question so far. I am not sure whether I understood the question correctly, but I believe you would like to set up connection string for your database. If that is the case, it is turned off by default in VIVO 1.12 (TDB is used as a default option). However, you can use SDB based on some relational database management system. You can find instructions for MySQL at https://wiki.lyrasis.org/display/VIVODOC112x/Jena+SDB+and+MySQL+setup.

**Comment by max1c** [comment]
Hi Chenejac,

I believe I was able to resolve my issue by converting the database using jena2tools and importing it with the jena3tools. 

Thank you,

Maxim
