### ISSUE TITLE
Add licence files for vivo-languages and vitro-languages

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3692]
**Is your feature request related to a problem? Please describe.**
Currently there is no licence file in https://github.com/vivo-project/VIVO-languages and https://github.com/vivo-project/Vitro-languages, and https://github.com/vivo-project/sample-data has a licence differing from the main repositories VIVO and Vitro. This makes (re)distribution of the content potentially complicated and should be resolved.

**Describe the solution you'd like**
A licence should be given to the repos in alignment to the other VIVO related repos.

**Describe alternatives you've considered**
Apache or BSD are the two options to be considered.

**Additional context**
Related issue: https://github.com/vivo-project/VIVO/issues/2345

**Comment by chenejac** [comment]
We are going to merge languages into VIVO/Vitro repositories, therefore, this issue is not active anymore.
