### ISSUE TITLE
Transforming vitro-dynamic-api.owl to vitro-dynamic-api.n3

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3701]
**Is your feature request related to a problem? Please describe.**
The xml notation of rdf is not so human-readable.

**Describe the solution you'd like**
It should be transformed to the n3 notation. There are online tools, Jena and other tools which might be used to automatize this transformation.

**Comment by litvinovg** [comment]
Fixed in https://github.com/vivo-project/Vitro/commit/5a1e1f50a71c179379370430d2efab9d4a1a2921
