### ISSUE TITLE
Language tags are added to string data properties when created via the web interface

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3717]
**Describe the bug**
Language tags are added to string data properties when created via the web interface the same way untyped literals get language tags.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add string data property value
2. View individual profile in RDF format and verify that language tag has been added to data property.

**Expected behaviour**
After adding a value through the web interface, the lingual tag should not appear.

**Comment by chenejac** [comment]
resolved with https://github.com/vivo-project/Vitro/pull/296
