### ISSUE TITLE
Dynamic API request processing attempting to mutate request parameters

### ISSUE THREAD

**Issue by wwelling** [vivo-project/VIVO#3718]
While processing request for dynamic API the resource id is extracted from the path and added to the request parameter map. This is an exception attempting to modify request parameter map.

The solution will be to return the resource id to the endpoint to pass into the operation input.

**Comment by chenejac** [comment]
@wwelling can you please also in PR attached to this issue change declaration and implementation of [getRestPRC method](https://github.com/vivo-project/Vitro/blob/0c289dd74d89fc056fcc1073ca095498a0764042/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/RESTEndpoint.java#L118), it should include requestPath.isResourceRequest() as a parameter, and make distinction between rpcOnGet and rpcOnGetAll.

**Comment by chenejac** [comment]
Resolved with https://github.com/vivo-project/Vitro/pull/307
