### ISSUE TITLE
Add information about reconciliation API to the VIVO documentation

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3729]
**Is your feature request related to a problem? Please describe.**
People doesn't seem to know that VIVO has a reconciliation API, which is one of the best things since the invention of sliced bread.

**Describe the solution you'd like**
Take https://wiki.lyrasis.org/display/VIVO/Extending+Google+Refine+for+VIVO as a basis and create a new page under https://wiki.lyrasis.org/display/VIVODOC113x/APIs.  The documentation should definitely contain the information that you have the API by simply adding /reconcile to your VIVO URL.

**Describe alternatives you've considered**
There is no alternative. Really.

**Comment by hauschke** [comment]
I only used it with OpenRefine, sorry. Documentation: https://docs.openrefine.org/manual/reconciling

**Comment by hauschke** [comment]
Draft: https://wiki.lyrasis.org/display/VIVODOC113x/Reconciliation+API

**Comment by chenejac** [comment]
> Draft: https://wiki.lyrasis.org/display/VIVODOC113x/Reconciliation+API

@hauschke thanks a lot for this draft version. I would add link to OpenRefine. Also, it might be confusing for someone why /fis/ is part of url, and might think /fis/reconcile is default path ending for getting api. Can we use https://openvivo.org/reconcile?

**Comment by hauschke** [comment]
Thanks for your feedback. A link to OpenRefine is in the text in the first sentence. I changed the example URL to OpenVIVO.

**Comment by chenejac** [comment]
Thank you very much. The default configuration for Vitro.reconcile.defaultTypeList has been turned off starting from VIVO 1.13.0 due to security reasons. Therefore, I have just slightly change a sentence in the Configuration of the VIVO Reconciliation API section.
