### ISSUE TITLE
Rename googleAnalytics.ftl to webAnalytics.ftl

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3735]
**Is your feature request related to a problem? Please describe.**
The googleAnalytics.ftl is already widely used with Matomo. It makes sense to have this named service agnostic.

**Describe the solution you'd like**
Rename googleAnalytics.ftl to webAnalytics.ftl.

**Describe alternatives you've considered**
If it is a lot of trouble for existing VIVO installations, this should be prioritized very low or not be done at all.

**Comment by chenejac** [comment]
Too risky to rename the file for existing VIVO customers, who might missed the information that the file is renamed and during the VIVO upgrade process forget to do that and miss logging of access to the VIVO application for some period. We decided to close this at the moment, it might be resolved by publishing VIVO 2.0 which should have completely redesigned UI.
