### ISSUE TITLE
German translation of strings in custom entry forms with autocomplete

### ISSUE THREAD

**Issue by tawahle** [vivo-project/VIVO#3740]
**Describe the bug**
Some of the strings in custom entry forms with autocomplete are not translated into German (and probably not into every other available language)

**To Reproduce**
1. Go for e.g. to "Create publication entry for ..."
2. Select a publication type: "Chapter"
3. Select a language: Deutsch (Deutschland)
5. See error: "Book" instead of "Buch"; "Publisher" instead of "Verlag" (There are probably more of such strings in other forms)
 
**Expected behavior**
The strings are showed in the language according to the chosen language version.

**Screenshots**
![image](https://user-images.githubusercontent.com/6906832/186393507-70697a24-f079-4fdf-a623-1a8d967510d7.png)

**Environment (please complete the following information):**
 - Browser: firefox
 - VIVO version: 1.11; 1.12.

**Comment by chenejac** [comment]
This should be fixed and be part of VIVO 1.14.0
