### ISSUE TITLE
Reconciliation API needs to deliver boolean values for "match"

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3741]
**Describe the bug**
According to https://reconciliation-api.github.io/specs/latest/ a match in the reconciliation API is described as "A boolean matching decision, which indicates whether the service considers this candidate good enough to be chosen as a correct match."

**To Reproduce**
1. Go to https://reconciliation-api.github.io/testbench/#/client/
2. Enter the URL of a VIVO reconciliation API, for example https://reconciliation-api.github.io/testbench/#/client/https%3A%2F%2Fvivo.tib.eu%2Ffis%2Freconcile
3. Enter "Hannover" in name, click on reconcile.
4. See the error message. 

**Expected behavior**
Replace `"match": "false"` with `"match": false`,

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1275231/186445993-b2ee1d38-3e87-419a-834d-cc99b31b3452.png)

**Environment (please complete the following information):**
 - VIVO 1.11 - 1.12, possibly earlier.

**Comment by chenejac** [comment]
Resolved with https://github.com/vivo-project/Vitro/pull/325
