### ISSUE TITLE
I forgot my vivo password

### ISSUE THREAD

**Issue by hidalgoo** [vivo-project/VIVO#3770]
**Is your feature request related to a problem? Please describe.**
Consider including the public option, on the constant queries of "I forgot my password", so that the user can carry out this process individually

**Comment by hidalgoo** [comment]
Consider including the public option, on the constant queries of "I forgot my password", so that the user can carry out this process individually

**Comment by chenejac** [comment]
Why this issue has been closed? There is an option for password reset, but I think it is available only for administrator (https://github.com/vivo-project/Vitro-languages/pull/46).

**Comment by hauschke** [comment]
This should be higher. This is a really a missing feature, and implementation is long overdue.
