### ISSUE TITLE
Rename i18n rdf files

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3803]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but i18n rdf files (nt, n3, ttl files located in the rdf/i18n/lang_Country subdirectories) shouldn't have information about the language in the name of the file, it is encoded in the full path and inside files via labels' language tags. 

**Describe the solution you'd like**
Remove language suffixes from i18n rdf files, for instance menu_en_US.nt should be menu.nt.
Language suffix should be present only in the language specific property files.

**Comment by michel-heon** [comment]
@chenejac 
I think it is best to keep the language labels on the filenames for the following reason.

In ontology engineering, to simplify directory navigation, it is common practice to copy all ontology files into a single directory. Therefore, it will not be possible to do this operation if all the files have the same name. 

I therefore recommend not to use this issue
