### ISSUE TITLE
Support link in footer is dead.

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3809]
**Describe the bug**
Support link in footer is dead.

**To Reproduce**
Click on "support" in the footer. it leads to http://www.vivoweb.org/support, which is redirected to https://vivo.lyrasis.org/support. Both do not exist. 

**Expected behavior**
https://github.com/vivo-project/Vitro/blob/main/webapp/src/main/webapp/templates/freemarker/page/partials/footer.ftl should be fixed, it should lead to a different page. Discussion with the communication IG is needed, if this link should lead somewhere (where?), if it is replaced or completely removed.
  
**Environment (please complete the following information):**
Every VIVO out of the box.

**Comment by chenejac** [comment]
@hauschke http://www.vivoweb.org/support works again. However, not sure this is a perfect solution.

**Comment by chenejac** [comment]
the link is working now, redirecting to https://vivo.lyrasis.org/contact/, where we adopted a support text a little bit and make contact form working again. @hauschke thanks for reporting this issue.
