### ISSUE TITLE
Increase password length limit

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3830]
**Is your feature request related to a problem? Please describe.**
Current password length is limited to only [12 characters](https://github.com/vivo-project/Vitro/blob/15cb4d74677c71181b6fcbd70dcd4273bed1cd69/api/src/main/java/edu/cornell/mannlib/vitro/webapp/beans/UserAccount.java#L18).

**Describe the solution you'd like**
Increase password length limit to 64 characters

**Comment by wwelling** [comment]
https://github.com/vivo-project/Vitro/pull/366
