### ISSUE TITLE
First class group label always have en-US tag

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3847]
**Describe the bug**
First class group label always have en-US language tag, no matter what current language is selected.

**To Reproduce**
1. Go to /listGroups
2. Switch to German
3. Add new group
4. Create label with DE suffix
5. Dump ApplicationMetatada graph, verify that label was created /ingest?action=outputModel&modelName=http%3A%2F
8. Check new label language tag

**Comment by brianjlowe** [comment]
Also affects property group labels and public descriptions.
