### ISSUE TITLE
Upload RDF data with blank nodes results in shredded ontology data in TBOX

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3871]
**Describe the bug**
Upload ontology data that contains blank nodes doesn't work. Data is getting shredded in TBOX

**To Reproduce**
1. Verify that TBOX doesn't contain any shredded data (Go to Ingest tools -> Manage Jena models -> click output model on  http://vitro.mannlib.cornell.edu/default/asserted-tbox )
2. Upload [dataset.ttl.zip](https://github.com/vivo-project/VIVO/files/11441776/dataset.ttl.zip) 
via siteAdmin -> Add/Remove RDF data 
3. Verify that uploaded data is shredded.
Go to Ingest tools -> Manage Jena models -> click output model on  http://vitro.mannlib.cornell.edu/default/asserted-tbox 
You should see something like that
![image](https://github.com/vivo-project/VIVO/assets/9299049/521d95eb-f7b6-409f-8ad4-5362d3e24647)

**Expected behavior**
The same data as attached to this issue should appear in TBOX

**Workaround**
1. Upload the same data via Ingest tools -> Manage Jena models -> add/remove RDF data.
2. Reload VIVO

**Comment by brianjlowe** [comment]
Looks like it starts going off the rails on line 34 of BulkOntModelImpl, where it calls GraphUtils.addInto(...) because the unwrapped graph is of type BulkGraphMem.  GraphUtils.addInto() then does a findAll() and iterates triple by triple.  Not sure yet what the intent was here; it seems to be taking a bulk-updating model and removing its bulk-updating nature.

**Comment by brianjlowe** [comment]
Resolved in PR https://github.com/vivo-project/Vitro/pull/393

**Comment by litvinovg** [comment]
I created a query to collect corrupted triples to remove from http://vitro.mannlib.cornell.edu/default/asserted-tbox graph.
[shredded-triples.rq.txt](https://github.com/vivo-project/VIVO/files/15073138/shredded-triples.rq.txt)
