### ISSUE TITLE
Update wiki SPARQL API example to explain use of kb-2 graph

### ISSUE THREAD

**Issue by brianjlowe** [vivo-project/VIVO#3901]
Prompted by https://github.com/vivo-project/VIVO/issues/3900

The SPARQL UPDATE wiki page at https://wiki.lyrasis.org/display/VIVODOC113x/SPARQL+Update+API uses the <http://vitro.mannlib.cornell.edu/default/vitro-kb-2> graph in its examples but doesn't explain why this particular graph IRI is significant.  It should be updated with a brief but prominent explanation of the fact that kb-2 is the only graph from which the GUI editor is able to remove triples, so data that is intended to be manually edited should be loaded here.

**Comment by brianjlowe** [comment]
Updated here: https://wiki.lyrasis.org/display/VIVODOC114x/SPARQL+Update+API

**Comment by chenejac** [comment]
Thanks @brianjlowe , I have also updated https://wiki.lyrasis.org/display/VIVODOC115x/SPARQL+Update+API
