### ISSUE TITLE
Update Tenderfoot to Bootstrap v5.X

### ISSUE THREAD

**Issue by hauschke** [vivo-project/VIVO#3912]
**Is your feature request related to a problem? Please describe.**

@gneissone commented in https://github.com/vivo-project/VIVO/issues/3910#issuecomment-1749553904
"Also, something to be said for the proposed update to wilma using Bootstrap 5, while tenderfoot is on v3."

It makes sense to use only one and an up-to-date version of bootstrap for officially supported themes.

**Describe the solution you'd like**
Update to v5.

**Additional context**
Tenderfoot is in production in a lot of institutions, including:

- https://vivo.hs-mittweida.de/vivo/ - @matthiasluehr 
- https://vivo.tib.eu/fis - @bkampe @litvinovg 
- https://forschungsatlas.fid-bau.de/ - @bkampe 
- https://fis.uni-osnabrueck.de/vivouos/ - @dofeldsc

**Comment by chenejac** [comment]
@hauschke we are planning to continue maintaining only one theme (wilma). Support for tenderfoot will be discontinued, meaning this theme will be moved to a https://github.com/vivo-community github repository as well as nemo theme, while wilma will be kept in the VIVO code base. The reason for this movement is capacity of VIVO maintainers group (for some new features we needed to align all themes). Wilma should incorporate good points from other themes (tenderfoot and nemo), one of them is responsiveness. Please list here all other request for making a comprehensive wilma theme.
