### ISSUE TITLE
Remove trash icon for some specific data types

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#3914]
**Is your feature request related to a problem? Please describe.**
Requested by Markus Kotte:

> Hi everyone, is it possible (within a reasonable amount of effort) to remove that trash can icon for some specific data types (not for all), so that the general user (e.g. the self-editors or everyone except admin) is not able to delete the data? It might be a useful feature for our VIVO. Thanks already.

**Describe the solution you'd like**
It would be great if this feature can be realized by using [ABAC](https://github.com/vivo-project/VIVO/pull/3887)

**Comment by litvinovg** [comment]
Should be resolved by https://github.com/vivo-project/Vitro/pull/398
