### ISSUE TITLE
Date time interval doesn't allow end date to be equal start date

### ISSUE THREAD

**Issue by litvinovg** [vivo-project/VIVO#3958]
**Describe the bug**
Date time interval doesn't allow end date to be equal start date

**To Reproduce**
1. Create a project
2. Click add date/time interval 
3. Enter the same year and month in start and end date values.

**Expected behavior**
Date time interval should allow to create and edit interval with equal start and end date

**Screenshots**
![grafik](https://github.com/vivo-project/VIVO/assets/9299049/02882cec-c318-4ede-8ebf-b6b8d0b16bb9)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Tomcat version 8.5
 - VIVO version 1.14.1-snapshot
 - Apache Solr 8.5

**Comment by milospp** [comment]
I Just tested and got the same error, also I noticed that it is possible to achieve similar effect if you specify the time range, for example:
<img width="978" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/8e3e8ce4-8911-4ad7-8945-b0f2704ede47">
<img width="324" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/f2c362a8-c100-4d17-b255-eb09755e6a3a">
But still, it is not possible to set the same day without time.


Also, there is a missing option for 0 minutes and 0 seconds options
<img width="266" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/d7c4f7c7-0576-4059-b7f9-0e16b5a5172c">
