### ISSUE TITLE
JIRA link in README is broken

### ISSUE THREAD

**Issue by chartgerink** [vivo-project/VIVO#3976]
**Describe the bug**
The [link to JIRA is broken in the readme](https://github.com/vivo-project/VIVO/blob/96c0b827567e07397d8b2999d943ebebc995ec52/README.md?plain=1#L112).

**Expected behavior**
I was interested to browse around and wanted to see what issues you had open. I figure it's the GitHub issues instead but the information is conflicting. 

---

Thanks for making VIVO 🙏

**Comment by chenejac** [comment]
@chartgerink thanks for reporting this. This has been already noticed and we created a PR fixing this - https://github.com/vivo-project/VIVO/pull/3954/files. It will be merged soon in the codebase.

**Comment by chenejac** [comment]
@chartgerink, the broken JIRA link has been fixed in the readme file. Thanks for reporting.
