### ISSUE TITLE
Improve documentation on file upload

### ISSUE THREAD

**Issue by markuskotte** [vivo-project/VIVO#3991]
**Is your feature request related to a problem? Please describe.**
https://wiki.lyrasis.org/display/VIVODOC114x/Uploading+files+associated+with+individuals

Some examples and screenshots about how to upload files (e.g. word or pdf files) would be helpful.
Currently there is just a technical configuration available.

**Comment by chenejac** [comment]
@markuskotte thanks for opening a ticket. I have added a couple of screenshots at https://wiki.lyrasis.org/display/VIVODOC114x/Uploading+files+associated+with+individuals. 

Please check whether it is better now.

**Comment by markuskotte** [comment]
@chenejac my first feedback on this:

I was able to upload and download files as root user, following your instructions on how to modify runtime.properties and property setting.
But for self-editor or editor, I'm not able to download the files: If I click on the URI of the uploaded file, I get to a page that is basically empty and displays no properties:

![image](https://github.com/user-attachments/assets/5fe3ce89-e099-4356-8a86-5a0323105eb1)

This is the same page as root user: I can download the file by clicking on "downloadLocation"
![image](https://github.com/user-attachments/assets/236d50c3-bcd6-427b-a3be-9f6b72a7a1d1)

The property that I use to upload the files has these settings:

![image](https://github.com/user-attachments/assets/9f52bf20-6f6d-4e96-bef4-1284d3f075fb)

I was thinking that changing the permissions for the property "downloadLocation" might help but I am not able to change them.

**Comment by chenejac** [comment]
@markuskotte I heard that you fixed this issue in collaboration with @litvinovg. Therefore, I am closing this ticket.
