### ISSUE TITLE
Default for new Link should be "URL" instead of "Faculty of 1000 Link"

### ISSUE THREAD

**Issue by markuskotte** [vivo-project/VIVO#3992]
**Is your feature request related to a problem? Please describe.**
Default for new Link should be "URL" instead of "Faculty of 1000 Link"
![image](https://github.com/vivo-project/VIVO/assets/120557228/23fe2910-6d4c-493a-9200-6aa5ab1347f5)

**Describe the solution you'd like**
Faculty of 1000 Link should be completely removed or at least ranked 2, so that URL is default setting when a link is added.
The current setting causes confusion for users who dont know what Faculty of 1000 means.

**Comment by hauschke** [comment]
It was decided in the ontology interest call that vivo:F1000Link will be deprecated.

https://wiki.lyrasis.org/display/VIVO/2024-07-03+Ontology+Interest+Group+Call
> https://github.com/vivo-project/VIVO/issues/3992 → Decision: f1000 url should be deprecated.
